6. HAFTA ÖDEV-2

 Sayılardan oluşan bir boyutlu array oluşturulur. Arrayi oluştururken sayıların veri tipini integer olarak belirtilir. Oluşturulan arrayin boyut, eleman sayısı bilgilerine bakılır. 
 İki ve üç boyutlu arrayler oluşturulur. Bu arraylerin boyut, eleman sayısı, satır, sütun bilgilerine ulaşılır. Arrayler üzerinde indexleme ve dilimleme(slicing) işlemi yapılır. 
 Numpy fonksiyonu kullanarak bir, iki ve üç boyutlu arrayler oluşturulur. Arrayler üzerinde indexleme ve dilimleme(slicing) işlemi yapılır 
 Sıfırlardan oluşan ve birlerden oluşan iki tane iki boyutlu array oluşturulur. Bu arrayler satır ve sütun bazında birleştirilir. 

In [1]:
import numpy as np

In [2]:
array1 = np.array([1,2,3,4,5], dtype = int)

In [4]:
print("1. Boyutlu Array:")
print("Array boyutu:", array1.ndim)
print("Eleman sayısı:", array1.size)
print("Array şekli:", array1.shape)

1. Boyutlu Array:
Array boyutu: 1
Eleman sayısı: 5
Array şekli: (5,)


In [5]:
#2 Boyutlu Array Oluşturma 
array2 = np.array([[1, 2, 3], [4, 5, 6]], dtype=int)

print("2. İki Boyutlu Array:")
print("Boyut:", array2.ndim)  
print("Eleman sayısı:", array2.size)  
print("Şekil:", array2.shape) 
print()

2. İki Boyutlu Array:
Boyut: 2
Eleman sayısı: 6
Şekil: (2, 3)



In [6]:
# 3. Üç Boyutlu Array Oluşturma
array3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]], dtype=int)

print("3. Üç Boyutlu Array:")
print("Boyut:", array3.ndim)  
print("Eleman sayısı:", array3.size)  
print("Şekil:", array3.shape)  
print()


3. Üç Boyutlu Array:
Boyut: 3
Eleman sayısı: 8
Şekil: (2, 2, 2)



In [7]:
#Indexleme ve Dilimleme İşlemleri
print("Indexleme ve Dilimleme İşlemleri:")

print("İki boyutlu arrayin [1,2] elemanı:", array2[1, 2])  
print("İki boyutlu arrayin ilk satırı:", array2[0, :])  
print()

# Üç boyutlu array için elemanlara erişim
print("Üç boyutlu arrayin [1,0,1] elemanı:", array3[1, 0, 1])  
print("Üç boyutlu arrayin ilk 'katmanı':\n", array3[0, :, :]) 
print()

Indexleme ve Dilimleme İşlemleri:
İki boyutlu arrayin [1,2] elemanı: 6
İki boyutlu arrayin ilk satırı: [1 2 3]

Üç boyutlu arrayin [1,0,1] elemanı: 6
Üç boyutlu arrayin ilk 'katmanı':
 [[1 2]
 [3 4]]



In [8]:
#Sıfırlardan ve Birlerden Oluşan Arrayler

zeros_array = np.zeros((2, 3), dtype=int)
print("Sıfırlardan Oluşan Array:\n", zeros_array)

ones_array = np.ones((2, 3), dtype=int)
print("Birlerden Oluşan Array:\n", ones_array)

vertical_stack = np.vstack((zeros_array, ones_array))
print("Satır Bazında Birleştirilmiş Array:\n", vertical_stack)

horizontal_stack = np.hstack((zeros_array, ones_array))
print("Sütun Bazında Birleştirilmiş Array:\n", horizontal_stack)

Sıfırlardan Oluşan Array:
 [[0 0 0]
 [0 0 0]]
Birlerden Oluşan Array:
 [[1 1 1]
 [1 1 1]]
Satır Bazında Birleştirilmiş Array:
 [[0 0 0]
 [0 0 0]
 [1 1 1]
 [1 1 1]]
Sütun Bazında Birleştirilmiş Array:
 [[0 0 0 1 1 1]
 [0 0 0 1 1 1]]
